# Generated by Django 3.1.3 on 2020-12-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogid', models.DecimalField(decimal_places=0, max_digits=6)),
                ('blogtitle', models.CharField(max_length=254)),
                ('blogtext', models.TextField()),
                ('blogimage_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('blogimage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
