# Generated by Django 3.1.3 on 2020-12-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogentry',
            options={'verbose_name_plural': 'Blogentries'},
        ),
    ]
