# Generated by Django 3.1.3 on 2020-12-30 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201227_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='blogdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='blogentry',
            name='blogposter',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
