# Generated by Django 3.1.3 on 2020-12-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citiesentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citiesid', models.DecimalField(decimal_places=0, max_digits=6)),
                ('citiestitle', models.CharField(max_length=254)),
                ('citiestext', models.TextField()),
                ('citiesimage_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('citiesimage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
