# Generated by Django 3.1.3 on 2020-12-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citiesentry',
            options={'verbose_name_plural': 'Citiesentries'},
        ),
        migrations.AddField(
            model_name='citiesentry',
            name='citiesimage2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='citiesentry',
            name='citiesimage2_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='citiesentry',
            name='citiesimage3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='citiesentry',
            name='citiesimage3_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='citiesentry',
            name='citiesimage4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='citiesentry',
            name='citiesimage4_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
