# Generated by Django 3.1.3 on 2020-12-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20201227_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citiesentry',
            name='citiesimage2',
        ),
        migrations.RemoveField(
            model_name='citiesentry',
            name='citiesimage2_url',
        ),
        migrations.RemoveField(
            model_name='citiesentry',
            name='citiesimage3',
        ),
        migrations.RemoveField(
            model_name='citiesentry',
            name='citiesimage3_url',
        ),
        migrations.RemoveField(
            model_name='citiesentry',
            name='citiesimage4',
        ),
        migrations.RemoveField(
            model_name='citiesentry',
            name='citiesimage4_url',
        ),
    ]
